### ISSUE TITLE
Introduce versioning/release strategy

### ISSUE THREAD

**Issue by bmuschko** [gradle-guides/gradle-guides-plugin#14]
The plugin was designed to publish a new version of the plugin with every commit. CI compiles the code, runs the tests, creates the archive and publishes it to the plugin portal. Publishing to the portal requires setting a new version for the project. Otherwise, publishing will fail and therefore the CI job.

The code is currently design to expect a change to the version with every commit. That's not desired. Sometimes you just want to update the docs or the build script but you don't necessarily want to publish a new version of the archive. The purpose of this issue to decouple these concerns.

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #306](https://github.com/gradle/guides/issues/306) via [**ZenHub**](https://www.zenhub.com/)
