### ISSUE TITLE
Community plugin author uses documentation plugins to produce documentation for their plugin

### ISSUE THREAD

**Issue by adammurdoch** [gradle-guides/gradle-guides-plugin#15]
It should be easy for a community plugin author to use the documentation plugins to produce some HTML documentation about their plugin, without that documentation necessarily being destined for or hosted on `guides.gradle.org`.

The documentation plugins should, perhaps optionally, produce HTML output that is styled to look something like the guide on `guides.gradle.org`. It should also not include the 'guides' logo in this instance.

**Comment by pioterj** [comment]
I agree. This is in line with what @eriwen was thinking too.

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #307](https://github.com/gradle/guides/issues/307) via [**ZenHub**](https://www.zenhub.com/)
