### ISSUE TITLE
.multi-language-text role has no effect

### ISSUE THREAD

**Issue by eskatos** [gradle-guides/gradle-guides-plugin#25]
The first part of the multi-language support documented here
https://github.com/gradle-guides/gradle-guides.github.io#adding-multi-language-samples-and-text doesn't seem to work.

I tried using the this Gradle Guides plugin version: https://plugins.gradle.org/plugin/org.gradle.guides.tutorial/0.12.0

The following:
```
[.multi-language-text.lang-groovy]
Some GROOVY paragraph.

[.multi-language-text.lang-kotlin]
Some KOTLIN paragraph.
```

Simply displays both paragraphs.

**Comment by eriwen** [comment]
gradle-guides-plugin v0.13.1 has finally been published that addresses this
