### ISSUE TITLE
Admonition titles formatting is off (asciidoctor's red)

### ISSUE THREAD

**Issue by eskatos** [gradle-guides/gradle-guides-plugin#27]
```adoc
[TIP]
.Knowing the type of a task
--
.. SNIP ..
--
```
renders to:

![image](https://user-images.githubusercontent.com/132773/42441812-5a25cb42-8369-11e8-8cb4-a10dca84de11.png)

**Comment by eriwen** [comment]
Fixed by updating CSS to latest

![screenshot 2018-08-16 08 53 13](https://user-images.githubusercontent.com/51534/44219833-d8594a80-a131-11e8-931e-290c83b91a70.png)
