### ISSUE TITLE
Handle case where remote sites don't support HEAD verb.

### ISSUE THREAD

**Issue by ysb33r** [gradle-guides/gradle-guides-plugin#4]
`checkLinks`: In some cases, like www.scalatest.org, using HEAD on a URL will return 404, but GET on the same URL will work. It might be worthwhile to have a failover where when HEAD fails, then falling back to GET is an option. In this case the call should not retrieve full content at the URL, but probably only the first 100 bytes.

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #308](https://github.com/gradle/guides/issues/308) via [**ZenHub**](https://www.zenhub.com/)
