### ISSUE TITLE
Should be able to find source of plugin from Gradle Plugin Portal

### ISSUE THREAD

**Issue by lptr** [gradle-guides/gradle-guides-plugin#55]
![image](https://user-images.githubusercontent.com/495366/69867628-a5e04c00-12a7-11ea-8c8b-a76a166c03e6.png)

This is currently all the information available about the plugin on the portal at https://plugins.gradle.org/plugin/org.gradle.samples. There is no link back to this repository, so it's really hard to find the source code. We should fix this in some way.

**Comment by lacasseio** [comment]
This is strange the `vcsUrl` is properly set: 

<img width="549" alt="Screen Shot 2019-11-29 at 4 29 10 PM" src="https://user-images.githubusercontent.com/22181740/69869135-73454c00-12c5-11ea-9f7d-9988c0a8717b.png">

**Comment by lacasseio** [comment]
It looks like it's the way the plugin portal deal with this. As shown by a [non-Gradle plugin](https://plugins.gradle.org/plugin/nebula.maven-nebula-publish):

<img width="602" alt="Screen Shot 2019-11-29 at 4 40 13 PM" src="https://user-images.githubusercontent.com/22181740/69869680-f6b36d00-12c6-11ea-8a6f-9c6028bfa017.png">

The result is the same:

<img width="721" alt="Screen Shot 2019-11-29 at 4 40 43 PM" src="https://user-images.githubusercontent.com/22181740/69869691-05018900-12c7-11ea-935a-3a2011ffa4a0.png">

Let's move the issue to the Plugin Portal.

**Comment by lacasseio** [comment]
Let's close this issue in favor of the feature request for the plugin portal: https://github.com/gradle/plugin-portal-requests/issues/19

**Comment by lptr** [comment]
Until the plugin portal issue is fixed, can we do the same as the Nebula plugin and set the `website` URL to point to GitHub?

**Comment by lacasseio** [comment]
[It looks like that won't be possible in a simple way](https://github.com/gradle/gradlecom/blob/master/gradle-plugins/publish-plugin/src/main/java/com/gradle/publish/PluginConfig.java). We would have to introduce a new project just for publishing the sample plugin and move the code around. I don't think it's "just" setting the `website` URL to point to GitHub for the sample plugin unless we want to change the website for all the guide plugins.

**Comment by lacasseio** [comment]
Let's change the `website` for all guide plugins and maybe mention the guides.gradle.org in the description if it can render well.

**Comment by lacasseio** [comment]
The fix is in master, the next release will have the change.
