### ISSUE TITLE
Polish code

### ISSUE THREAD

**Issue by bmuschko** [gradle-guides/gradle-guides-plugin#8]
- The Apache license header should not have a person-specific copyright. Let's use the same license header as in Gradle core. __(DONE!)__
- Upgrade to Gradle 4.1. __(DONE! Opened https://github.com/ysb33r/gradleTest/issues/78)__
- The plugins have a mix of `@CompileStatic` and `@CompileDynamic`. To ensure best binary compatibility they should only use `@CompileStatic` or be written in plain Java.
- Changes to `BasePlugin`:
    - `static final` fields should use `public` modifier.
    - Simply use return value of extension creation method and pass instance to where it is needed. Right now we have the same code multiple times to get the extension from the container.
- Changes to `GuidesExtension`:
    - The class doesn't actually use the `Project` instance passed in through constructor. It should be removed.
    - Uncommon formatting of Javadocs. The text should not start on same line as `/**`?
    - Move all fields to top of class for better readability.
    - Why is `contributeMessage` of type `Object` and not a `String`?
    - It seems to be that `contributeMessage` shouldn't really live in the extension.
    - Remove use of internal class `org.gradle.util.CollectionUtils`.
- Better Javadoc documentation e.g. on the class of testing plugin an indication which dependencies are added by the plugin.
- Dependencies on external plugins - are those really required?
- I feel torn about the declaration of guide type-specific plugin. Most of them actually don't add any logic.
- We'll need more tests for the plugin code. I'd prefer the use of TestKit. We should probably try to avoid the use of the external plugin `org.ysb33r.gradletest`.
- We might want to think about publishing the Javadocs or in this case the Groovydocs.
- `LICENSE.txt` should contain the full Apache 2 license agreement. __(DONE!)__
- `.travis.xml` should use `install=true` to avoid default execution of `assemble` task.
- I'd prefer if we could minimize the amount of external plugins that we'd don't have control over e.g. `cloudci` etc.

**Comment by ysb33r** [comment]
@bmuschko My feedback:
> The Apache license header should not have a person-specific copyright. Let's use the same license header as in Gradle core.

Yes.

> Upgrade to Gradle 4.0.

Yes

> The plugins have a mix of @CompileStatic and @CompileDynamic. To ensure best binary compatibility they should only use @CompileStatic or be written in plain Java.

Only private methods could be left with `@CompileDynamic`. Anyone is of course free to rewrite into Java if they so wish.

> Changes to BasePlugin:

No complaints
 
> Uncommon formatting of Javadocs. The text should not start on same line as /**?

Habit from old days.    

>     Move all fields to top of class for better readability.

I personally hate that, but please feel free to reformat.

>       Why is contributeMessage of type Object and not a String?

Lazy evaluation.

>        Remove use of internal class org.gradle.util.CollectionUtils.

I thought `org.gradle.util` is still considered public. If not, make this a public available API, it is damn useful. Many people uses it.

>    Better Javadoc documentation e.g. on the class of testing plugin an indication which dependencies are added by the plugin.
  
Can be done.

> Dependencies on external plugins - are those really required?

Yes, unless you really would like to rewrite all of the functionality they provide.

> I feel torn about the declaration of guide type-specific plugin. Most of them actually don't add any logic.

I know, but they were done in that way to classify the three kind and then to add specifics as things evolved. Curretnly the biggest differnece is that they change the asciidoctor attributes.

>    We'll need more tests for the plugin code. I'd prefer the use of TestKit. We should probably try to avoid the use of the external plugin org.ysb33r.gradletest.

We acually need both, I think.

>    We might want to think about publishing the Javadocs or in this case the Groovydocs.

Wasn't sure where to publish it to.

> LICENSE.txt should contain the full Apache 2 license agreement.

Yes

>    .travis.xml should use install=true to avoid default execution of assemble task.

Also need to add it to the three guide templates.

>    I'd prefer if we could minimize the amount of external plugins that we'd don't have control over e.g. cloudci etc.

It's up to you.

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #212](https://github.com/gradle/guides/issues/212) via [**ZenHub**](https://www.zenhub.com/)
